### ISSUE TITLE
No notifications get e-mailed on new forum posts

### ISSUE THREAD

**Issue by alcarola** [open-lms-open-source/moodle-mod_hsuforum#51]
Hi, and thanks for the awesome forum!

The plugin seems to work fine for me on Moodle 4.1.8 (Build: 20231222), apart from the fact that I do not get any e-mail notifications sent out, even if I am subscribed to the forum. (I have turned off digests, because as the teacher in high-paced course, I prefer to be e-mailed right away if somebody posts something.)

Am I just missing something, or is this a bug? Can anybody help me to get this fixed? I have tried both googling and searching the issues for this git repository, but I have not found any clues.

Thank you for any help!
Mikael

**Comment by christianabila** [comment]
I'm getting the following error message from the task log (Moodle 4.1.8, Pluginversion 2023121800):

```
Scheduled task failed: Open Forum mailings and maintenance jobs (mod_hsuforum\task\cron_task),Class "core\cron" not found
Backtrace:
* line 45 of /mod/hsuforum/classes/task/cron_task.php: call to hsuforum_cron()
* line 263 of /lib/cronlib.php: call to mod_hsuforum\task\cron_task->execute()
* line 120 of /lib/cronlib.php: call to cron_run_inner_scheduled_task()
* line 73 of /lib/cronlib.php: call to cron_run_scheduled_tasks()
* line 178 of /admin/cli/cron.php: call to cron_run()
```

**Comment by alcarola** [comment]
@christianabila, thank you so much for drawing my attention to the task log!

By replacing every occurence of "\core\cron::setup_user(" by "cron_setup_user(" in MOODLEROOT/mod/hsuforum/lib.php, this problem was fixed. I attach a zipped diff to this post.

This fixed the daily digests, but I still would like to have a notification immediately when somebody posts to the forum. I am subscribed to the forum, and reading the hsuforum code, I get the impression that I should get individual notifications for new posts, but still I only get the daily digests. 

The backtrace that you posted concerned the daily digests. Do you have any suggestion how I could troubleshoot the instant notifications?

[lib.php.diff.zip](https://github.com/open-lms-open-source/moodle-mod_hsuforum/files/14116962/lib.php.diff.zip)

**Comment by stefan612** [comment]
I am running into the same problem.
@alcarola Have you been able to solve the problem with instant notification?
It seems rare... by checking the task in GUI it should run every minute. But it shows that it only runs once per day.

**Comment by alcarola** [comment]
@stefan612, unfortunately, I have no new progress on this issue...

**Comment by stefan612** [comment]
@alcarola I just checked again... i now receive Emails based on the cron / scheduled_task settings.
Email notification works  as one would expect.

**Comment by alcarola** [comment]
Great, thanks for the update, @stefan612!

**Comment by stefan612** [comment]
Maybe there is a wrong setting in your scheduled task configuration which does the task just once per day.

**Comment by alcarola** [comment]
That does not seem to be the problem. According to _Administration > Site administration > Server > Tasks > Scheduled tasks_, the hsuforum task is executed successfully once a minute, but the messages are simply not sent out. See the attached screenshots.

![Screenshot from 2024-06-18 10-26-54](https://github.com/open-lms-open-source/moodle-mod_hsuforum/assets/1645276/be539172-9b3a-4be2-a69a-4c779e7f4c68)

![Screenshot from 2024-06-18 10-27-43](https://github.com/open-lms-open-source/moodle-mod_hsuforum/assets/1645276/4d1d5777-8efe-4c24-ba8c-6349cd92ac81)

**Comment by alcarola** [comment]
Update: I was wrong, probably there was just some editing time that did not pass before I answered.

The problem indeed seems to be resolved now! Many thanks to those who fixed it!

**Comment by sennewood** [comment]
We are running Moodle 4.1.13 and plugin version 2024040200 and still have this issue:

```plain
Execute scheduled task: Moodlerooms Advanced Forum E-Mail- und Wartungs-Jobs (mod_hsuforum\task\cron_task)
... started 13:55:01. Current memory use 24.2 MB.
Debugging increased temporarily due to faildelay of 86400
... used 5 dbqueries
... used 0.030110120773315 seconds
Scheduled task failed: Moodlerooms Advanced Forum E-Mail- und Wartungs-Jobs (mod_hsuforum\task\cron_task),Class 'core\cron' not found
Backtrace:
* line 45 of /mod/hsuforum/classes/task/cron_task.php: call to hsuforum_cron()
* line 263 of /lib/cronlib.php: call to mod_hsuforum\task\cron_task->execute()
* line 120 of /lib/cronlib.php: call to cron_run_inner_scheduled_task()
* line 73 of /lib/cronlib.php: call to cron_run_scheduled_tasks()
* line 178 of /admin/cli/cron.php: call to cron_run()
```
